### PR TITLE
Avatar editor

### PR DESCRIPTION
**Pull request by letmaik**
grafik

This adds an editor for tweaking existing avatars where the editor is synchronized with the camera view. On every drag end of a skeleton point the avatar is sent to the main window. It also adds a paint option to change the color of illustration shapes.

Some keypoints in the skeleton have equivalent keypoints in the illustration. I'm linking them together, so that when a skeleton point is dragged (and only those are draggable) then the position of any name-matching illustration keypoints are set to the same position. Since they don't always match exactly in the original SVGs I'm assuming this is intentional and has some purpose. But I haven't understood that and tried to simplify it.

### CODE REVIEW

**Review by dmey — APPROVED** [review]
Depends on #29.

**Comment by letmaik** [comment]
It's the other way around I think. Your PR #29 depends on this PR.

**Comment by dmey** [comment]
> It's the other way around I think. Your PR #29 depends on this PR.

A bit confusing perhaps but what I meant is that the meting of this PR depends on merging #29 into this first, then can merge into master.

**Comment by letmaik** [comment]
Makes sense, I hadn't checked the target branch!

**Pull request merged**
